apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrs-kafka-producer
  labels:
    app: hrs-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hrs-kafka-producer
  template:
    metadata:
      labels:
        app: hrs-kafka-producer
    spec:
      containers:
        - name: kibana
          image: localhost:5000/hrs-kafka-producer:1.0.0
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: KAFKA_BROKER_LIST
              value:  "52.172.24.230:9092,13.71.124.119:9092,52.140.16.51:9092"
            - name: EVENT_TOPIC
              value: "hrs-event"
            - name: ALARM_TOPIC
              value: "hrs-alarm"
